### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by adgbu** [fabriciochamon/DearPyGui_Extend#1]
Hi!
I'm trying to run the layout example but it immediately crashes with a Segfault. I have a virtual environment with Python 3.9.16 + dearpygui + some other requirements installed via pip. I've cloned ```DearPyGui_Extend``` repo and installed into the virtual env with ```python setup.py install```. After that I try to run the layout example, which generates a Segfault. No other output. 

I get the same on "native" Windows 10 (VSCode) aswell as under a WSL2 Ubuntu VM. Is it something I've done or is it a bug?

**Comment by fabriciochamon** [comment]
Hi. Could you try an isolated venv with just DearPyGui_Extend installed ? (It should also install the additional requirements: dpg/fileseq).

I've just tested a VM with Ubuntu 22, python 3.9.17, and venv. Running the layout examples runs fine, so I assume it is not an user error on your side, but rather some incompatibility with a pre-installed version of dearpygui.

**Comment by adgbu** [comment]
My bad. It was something in my code. The *vanilla* examples worked.

Now that I have tried it i realise that still cannot control the height of rows. They are always equally distributed. Same limitation as plain dpg table, which makes sense for a wrapper. :) 

I'm looking for a way to split a container horizontally in upper and lower part, where the split is resizeable and the container should fill available space in the window. (Like one can do with table columns horizontally).

**Comment by fabriciochamon** [comment]
That's correct, it does not have any support for row resizing, as you said, its a limitation of dpg. I'll have a look at the global mouse event and see whether I can grab the current row being clicked on, maybe fire up a custom resize callback. 
I feel this is currently not possible in dearpygui, but have to dig deeper.
