### ISSUE TITLE
FileBrowser should include a UUID in its tag prefix

### ISSUE THREAD

**Issue by ndahn** [fabriciochamon/DearPyGui_Extend#4]
The [FileBrowser](https://github.com/fabriciochamon/DearPyGui_Extend/blob/main/dearpygui_extend/file_browser.py#L63) should include a UUID or similar in its `tag_prefix`. Right now it is not possible to have more than one file browser.

Unfortunately, a simple fix like below will cause other issues, e.g. textures not being found anymore. It would probably be a good idea to store all textures independent from FileBrowser instances anyways. 

```python
tag_prefix = 'dpge_filebrowser_' + str(dpg.generate_uuid())
```

**Comment by fabriciochamon** [comment]
Thanks for pointing out, I'll work on a fix for that.

**Comment by juzt3** [comment]
please fix this

**Comment by fabriciochamon** [comment]
Fixed. Please update to newest version.

Now you can either: 
1. provide your own tag for each filebrowser instance (clashing tags should be handled by user)
2. do not provide a tag and have dpge to generate it automatically based on uuid

Please check the 2 extra sample files I've added in the "examples/file_browser" folder.
