### ISSUE TITLE
DearPyGui_Extend does not support DearPyGui v2

### ISSUE THREAD

**Issue by Phortran** [fabriciochamon/DearPyGui_Extend#5]
DarPyGui v2 is finally out and they have introduced some breaking changes.

For example, the constant `dpg.mvKey_Shift` doesn't exist anymore and should be replaced with either `dpg.mvKey_LShift` or `dpg.mvKey_RShift`.

I haven't spent time looking for more issues but I expect more issues to pop up.

**Comment by fabriciochamon** [comment]
Fixed.
